bio: "Nevada is an actor – improviser – writer living in NYC. You can see her perform sketch at The PIT and UCB NY. Follow her on <a href='https://www.instagram.com/bklyncowgirl/' target='_blank'>instagram</a> for show updates and for a not at all insane number of photos of her cat, Kevin."

resume: Nevada_Caldwell_Acting_Resume_2016.pdf

photos:
  - Nevada_Caldwell_Headshot_2015.jpg

clips:
  - name: Army Wives
    id: 177852230
  - name: Waste-Free Nation
    id: 177853595
  - name: Falcon Man
    id: 177863331
  - name: Subway Makeup
    id: 177865026
