bio: "Nevada is an actor - writer - filmmaker living in NYC. Follow her on <a href='https://www.instagram.com/therealnevada' target='_blank'>instagram</a> for screening/show updates and for a not at all insane number of photos of her cat, Kevin."

resume: Nevada_Caldwell_Acting_Resume_2016.pdf

photos:
  - Nevada_Caldwell_Headshot_2015.jpg

clips:
  - name: Army Wives
    id: 177852230
  - name: Waste-Free Nation
    id: 177853595
  - name: Falcon Man
    id: 177863331
  - name: Subway Makeup
    id: 177865026
