bio: "Nevada has lived and performed in most of the weird states. A gypsy since birth, she currently splits her time between NYC, Orlando, and Atlanta. You can see her perform on stage at the People’s Improv Theater, Upright Citizen’s Brigade, and Annoyance Theater (NYC). She is equally gifted as an actor, singer, writer, and director and is proud mom to Cornelius Augustus III – a handsome ficus tree."

resume: Nevada_Caldwell_Acting_Resume_2016.pdf

photos:
  - Nevada1-1.jpg
  - Nevada2-1.jpg

clips:
  - name: Army Wives
    id: 177852230
  - name: Waste-Free Nation
    id: 177853595
  - name: Falcon Man
    id: 177863331
  - name: Subway Makeup
    id: 177865026
