backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Media files will be stored in the repo under this folder structure
media_folder: '_assets/images'
public_folder: 'assets/images'

collections:
  - label: 'Website Settings'
    name: 'website-settings'
    files:
      - label: 'SEO Settings'
        name: 'seo-settings'
        file: '_data/seo.json'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: Description
            name: description
            widget: 'string'
            pattern: ['^.{120,158}$', 'Must be between 120 and 158 characters.']
      - label: 'Contact Info'
        name: 'contact-settings'
        file: '_data/contact.json'
        fields:
          - label: Email
            name: email
            widget: string
          - label: Instagram
            name: instagram
            widget: string
          - label: Facebook
            name: facebook
            widget: string

  - label: Content
    name: content
    files:
      - label: Bio
        name: bio
        file: '_data/bio.json'
        fields:
          - label: Bio
            name: bio
            widget: markdown

      - label: Uploads
        name: uploads
        file: '_data/content.json'
        fields:
          - label: Resume
            name: resume
            allow_multiple: false
            widget: file

          - label: Headshot
            name: headshot
            allow_multiple: false
            widget: image

      - label: Videos
        name: videos
        file: '_data/videos.json'
        fields:
          - label: Reel
            name: reel
            hint: 'Enter the Vimeo ID of your reel here.'
            widget: string
          - label: Clips
            name: clips
            widget: list
            fields:
              - label: Clip Name
                name: clipname
                widget: string
              - label: Clip ID
                name: clipid
                widget: string
              - label: Clip Thumbnail URL
                name: clipthumb
                widget: hidden
                default: ''

      - label: 'Footer Info'
        name: 'footer-settings'
        file: '_data/footer.json'
        fields:
          - label: Representation
            name: representation
            widget: list
            fields:
              - label: Location
                name: location
                widget: string
              - label: Agency
                name: agency
                widget: string
              - label: Agent
                name: agent
                widget: string
              - label: Phone
                name: phone
                widget: string
          - label: Links
            name: links
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Link
                name: link
                widget: string
